<<<<<<< HEAD
# Copyright 2023 Manna Harbour
||||||| b0fd704
# Copyright 2022 Manna Harbour
=======
# Copyright 2024 Manna Harbour
>>>>>>> upstream/master
# https://github.com/manna-harbour/miryoku

name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
<<<<<<< HEAD
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
||||||| b0fd704
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
=======
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2","zmkfirmware/zmk/main caksoylar/zmk/feat/mouse-keys-3.2"]'
>>>>>>> upstream/master
