# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Xiao Shields'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao"]'
      shield: '[
<<<<<<< HEAD
        "chipper_left","chipper_right",
||||||| b0fd704
=======
        "bad_wings",
        "chipper_left","chipper_right",
>>>>>>> upstream/master
        "clog_v2_left","clog_v2_right",
        "hummingbird",
<<<<<<< HEAD
        "kpukboard_left","kpukboard_right",
||||||| b0fd704
=======
        "klein_left","klein_right",
        "kpukboard_left","kpukboard_right",
>>>>>>> upstream/master
        "revxlp",
        "rommana_left","rommana_right",
        "totem_left","totem_right",
        "xmk",
        "zaphod_lite"
      ]'
