# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test Build'
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == 'issmirnov'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v1_left","corneish_zen_v1_right"]'
      alphas: '["BEAKL15"]'
      clipboard: '["mac"]'
